### ISSUE TITLE
Frontend Création d'une annonce

### ISSUE THREAD

**Issue by QuentinForestier** [FindYourPet-ch/FindYourPet#149]
![image](https://user-images.githubusercontent.com/61196479/151001471-28c1a2fc-5117-4acf-bc95-057eac2f3541.png)

On peut créer une annonce que si le site est en anglais..

**Comment by QuentinForestier** [comment]
mettre male female dans verify input

**Comment by LordTT** [comment]
Ce bug arrive aussi au niveau des filtres
